[workspace]
members = ["crates/otpauth", "crates/otpauth-cli"]

[workspace.package]
authors = ["Liu Bowen <asyncmode@outlook.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
